Consistency in redirection directives

diff --git a/bluetooth_play_pause_toggle b/bluetooth_play_pause_toggle
--- a/bluetooth_play_pause_toggle
+++ b/bluetooth_play_pause_toggle
@@ -30,8 +30,8 @@ do
             mac_address=${OPTARG}
             ;;
         \?)
-            echo "Invalid option: -$OPTARG" 1>&2
-            print_usage 1>&2
+            echo "Invalid option: -$OPTARG" >&2
+            print_usage >&2
             exit 1
             ;;
     esac
