Whitespace error

diff --git a/crypt b/crypt
--- a/crypt
+++ b/crypt
@@ -16,7 +16,7 @@ do
             exit 0
             ;;
         \?)
-            echo "Invalid option: -$OPTARG" >&2 
+            echo "Invalid option: -$OPTARG" >&2
             exit 1
             ;;
     esac
