Whitespace errors

diff --git a/dfzf b/dfzf
--- a/dfzf
+++ b/dfzf
@@ -23,7 +23,7 @@ do
             cache_dir="${OPTARG}"
             ;;
         \?)
-            echo "Invalid option: -$OPTARG" >&2 
+            echo "Invalid option: -$OPTARG" >&2
             exit 1
             ;;
     esac
