Whitespaces

diff --git a/trimd b/trimd
--- a/trimd
+++ b/trimd
@@ -20,7 +20,7 @@ do
             count=${OPTARG}
             ;;
         \?)
-            echo "Invalid option: -$OPTARG" >&2 
+            echo "Invalid option: -$OPTARG" >&2
             exit 1
             ;;
     esac
